[package]
name = "mailform-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
clap = { version = "4", features = ["derive", "env"], optional = true }
clap-serde-derive = { version = "0.2", optional = true }
lettre = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
snafu = { version = "0.7", features = ["rust_1_61"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[features]
cli = ["clap", "clap-serde-derive"]
